"use client";

import { CalendarDays, Check, Search, Trash2, X } from "lucide-react";
import { useEffect, useState } from "react";
import { hideDoctorAppointment, loadDoctorAppointments, subscribeToBookingChanges, updateDoctorAppointmentStatus } from "@/features/booking/storage";
import { useDoctorAuth } from "@/features/doctor/hooks/doctor-auth-context";
import type { BookedAppointment } from "@/features/booking/types";

type StatusFilter = "all" | BookedAppointment["status"];
const statusClasses = { confirmed: "bg-emerald-50 text-emerald-800 ring-emerald-200", pending: "bg-amber-50 text-amber-800 ring-amber-200", cancelled: "bg-stone-100 text-stone-600 ring-stone-200" };

export default function DoctorAppointments() {
  const { doctor } = useDoctorAuth();
  const [status, setStatus] = useState<StatusFilter>("all");
  const [query, setQuery] = useState("");
  const [date, setDate] = useState("");
  const [, setVersion] = useState(0);
  useEffect(() => subscribeToBookingChanges(() => setVersion((current) => current + 1)), []);
  const appointments = doctor ? loadDoctorAppointments(doctor.id).sort((left, right) => `${right.date} ${right.time}`.localeCompare(`${left.date} ${left.time}`)) : [];
  const filtered = appointments.filter((appointment) => (status === "all" || appointment.status === status) && (!date || appointment.date === date) && (!query.trim() || `${appointment.patientName} ${appointment.patientPhone} ${appointment.visitType}`.toLowerCase().includes(query.trim().toLowerCase())));
  function updateStatus(id: string, nextStatus: "confirmed" | "cancelled"): void { if (doctor) updateDoctorAppointmentStatus(doctor.id, id, nextStatus); }
  function deleteAppointment(id: string): void { if (doctor) hideDoctorAppointment(doctor.id, id); }

  return <main className="min-h-screen bg-[var(--canvas)] px-4 py-5 sm:px-8 sm:py-8 lg:px-12"><div className="mx-auto max-w-6xl"><header className="border-b border-[var(--line)] pb-6"><p className="text-sm font-medium uppercase tracking-[.18em] text-[var(--brand)]">Doctor portal</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">All Appointments</h1><p className="mt-2 text-[var(--muted)]">Review and filter appointments booked with your practice.</p></header>
    <section className="mt-7 rounded-xl border border-[var(--line)] bg-white p-4 shadow-sm sm:p-5" aria-label="Appointment filters"><div className="grid gap-3 lg:grid-cols-[1fr_auto_auto]"><label className="relative"><span className="sr-only">Search appointments</span><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[var(--muted)]" aria-hidden="true" /><input className="w-full rounded-lg border border-[var(--line)] bg-[var(--canvas)] py-2.5 pl-10 pr-3 text-sm outline-none focus:border-[var(--brand)] focus:ring-4 focus:ring-emerald-100" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search patient, phone, or visit type" /></label><label className="text-sm font-medium"><span className="sr-only">Filter by date</span><input className="w-full rounded-lg border border-[var(--line)] bg-[var(--canvas)] px-3 py-2.5 text-sm font-normal outline-none focus:border-[var(--brand)] focus:ring-4 focus:ring-emerald-100" type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label className="text-sm font-medium"><span className="sr-only">Filter by status</span><select className="w-full rounded-lg border border-[var(--line)] bg-[var(--canvas)] px-3 py-2.5 text-sm font-normal outline-none focus:border-[var(--brand)] focus:ring-4 focus:ring-emerald-100" value={status} onChange={(event) => setStatus(event.target.value as StatusFilter)}><option value="all">All statuses</option><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="cancelled">Cancelled</option></select></label></div><p className="mt-3 text-sm text-[var(--muted)]">Showing {filtered.length} of {appointments.length} appointments</p></section>
    <section className="mt-5 overflow-hidden rounded-xl border border-[var(--line)] bg-white shadow-sm" aria-live="polite">{filtered.length === 0 ? <div className="px-6 py-14 text-center"><CalendarDays className="mx-auto size-8 text-[var(--brand)]" aria-hidden="true" /><p className="mt-4 font-semibold">No appointments found</p><p className="mt-1 text-sm text-[var(--muted)]">Try changing your filters, or appointments booked by patients will appear here.</p></div> : <ul className="divide-y divide-[var(--line)]">{filtered.map((appointment) => <li className="grid gap-4 px-5 py-5 sm:grid-cols-[1.1fr_.9fr_auto] sm:items-center sm:px-6" key={appointment.id}><div className="flex min-w-0 items-center gap-3"><div className="grid size-11 shrink-0 place-items-center rounded-full bg-emerald-100 font-semibold text-[var(--brand-deep)]">{initials(appointment.patientName)}</div><div className="min-w-0"><p className="truncate font-semibold">{appointment.patientName}</p><p className="mt-0.5 truncate text-sm text-[var(--muted)]">{appointment.patientPhone} · {appointment.visitType}</p></div></div><div><p className="font-medium">{formatDate(appointment.date)} · {appointment.time}</p><p className="mt-0.5 text-sm text-[var(--muted)]">{appointment.note || "No visit note provided"}</p></div><div className="flex flex-wrap items-center justify-end gap-2"><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-medium capitalize ring-1 ring-inset ${statusClasses[appointment.status]}`}>{appointment.status}</span>{appointment.status === "pending" ? <><button className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-2.5 py-1.5 text-xs font-semibold text-white hover:bg-emerald-700" type="button" onClick={() => updateStatus(appointment.id, "confirmed")}><Check className="size-3.5" />Confirm</button><button className="inline-flex items-center gap-1 rounded-lg border border-red-200 px-2.5 py-1.5 text-xs font-semibold text-red-700 hover:bg-red-50" type="button" onClick={() => updateStatus(appointment.id, "cancelled")}><X className="size-3.5" />Cancel</button></> : <button className="inline-flex items-center gap-1 rounded-lg border border-[var(--line)] px-2.5 py-1.5 text-xs font-semibold text-[var(--muted)] hover:border-red-200 hover:bg-red-50 hover:text-red-700" type="button" onClick={() => deleteAppointment(appointment.id)}><Trash2 className="size-3.5" />Delete</button>}</div></li>)}</ul>}</section></div></main>;
}

function initials(name: string): string { return name.split(" ").filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase(); }
function formatDate(date: string): string { return new Date(`${date}T00:00:00`).toLocaleDateString("en-IN", { weekday: "short", month: "short", day: "numeric", year: "numeric" }); }
