"use client";

import Link from "next/link";
import { CalendarPlus, Clock3, Trash2 } from "lucide-react";
import { useMemo, useState, type FormEvent } from "react";
import { loadDoctorAvailability, removeDoctorAvailabilitySlot, saveDoctorAvailability } from "@/features/doctor/availability";
import { updateDoctorProfile } from "@/features/doctor/api/profile";
import { saveDirectoryDoctor } from "@/features/doctor/directory";
import { useDoctorAuth } from "@/features/doctor/hooks/doctor-auth-context";
import type { DoctorAvailabilitySlot, DoctorProfileFields } from "@/features/doctor/types";

const weekdayNames = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const fieldClass = "mt-1.5 w-full rounded-lg border border-[var(--line)] bg-[var(--canvas)] px-3 py-2.5 text-sm outline-none focus:border-[var(--brand)] focus:bg-white focus:ring-4 focus:ring-emerald-100";

export default function DoctorProfile() {
  const { doctor, updateDoctor } = useDoctorAuth();
  const [profile, setProfile] = useState<DoctorProfileFields | null>(() => doctor);
  const [slots, setSlots] = useState<DoctorAvailabilitySlot[]>(() => doctor ? loadDoctorAvailability(doctor.id) : []);
  const [message, setMessage] = useState("");
  const [profileError, setProfileError] = useState("");
  const [isSavingProfile, setIsSavingProfile] = useState(false);
  const [slotError, setSlotError] = useState("");
  const [slotForm, setSlotForm] = useState({ date: today(), startTime: "09:00", endTime: "09:30", isRecurring: false, daysOfWeek: [] as number[], endDate: addDays(28) });

  const availableCount = useMemo(() => slots.filter((slot) => slot.status === "available").length, [slots]);
  if (!doctor || !profile) return null;
  const doctorId = doctor.id;

  function updateProfileField(field: keyof DoctorProfileFields, value: string): void { setProfile((current) => current ? { ...current, [field]: field === "experienceYears" ? Number(value) : value } : current); }
  async function saveProfile(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); if (!profile) return; setProfileError(""); setIsSavingProfile(true); try { const savedProfile = await updateDoctorProfile(doctorId, profile); saveDirectoryDoctor(savedProfile); updateDoctor(savedProfile); setProfile(savedProfile); setMessage("Profile saved."); } catch (error: unknown) { setProfileError(error instanceof Error ? error.message : "Unable to save your profile"); } finally { setIsSavingProfile(false); } }
  function toggleDay(day: number): void { setSlotForm((current) => ({ ...current, daysOfWeek: current.daysOfWeek.includes(day) ? current.daysOfWeek.filter((item) => item !== day) : [...current.daysOfWeek, day] })); }
  function addSlots(event: FormEvent<HTMLFormElement>): void {
    event.preventDefault(); setSlotError("");
    if (slotForm.endTime <= slotForm.startTime) return setSlotError("End time must be after the start time.");
    if (slotForm.date < today()) return setSlotError("Choose today or a future date.");
    if (slotForm.isRecurring && (!slotForm.endDate || slotForm.endDate < slotForm.date || slotForm.daysOfWeek.length === 0)) return setSlotError("Choose at least one day and a valid recurrence end date.");
    const dates = slotForm.isRecurring ? recurringDates(slotForm.date, slotForm.endDate, slotForm.daysOfWeek) : [slotForm.date];
    const newSlots = dates.map((date, index): DoctorAvailabilitySlot => ({ id: `availability-${Date.now()}-${index}`, doctorId, date, startTime: slotForm.startTime, endTime: slotForm.endTime, isRecurring: slotForm.isRecurring, recurrenceRule: slotForm.isRecurring ? { frequency: "weekly", daysOfWeek: slotForm.daysOfWeek, endDate: slotForm.endDate } : undefined, status: "available" }));
    const merged = [...slots, ...newSlots]; saveDoctorAvailability(merged); setSlots(merged); setMessage(`${newSlots.length} availability ${newSlots.length === 1 ? "slot" : "slots"} added.`);
  }
  function deleteSlot(slot: DoctorAvailabilitySlot): void { if (slot.status === "booked") return; removeDoctorAvailabilitySlot(doctorId, slot.id); setSlots((current) => current.filter((item) => item.id !== slot.id)); }

  return <main className="min-h-screen bg-[var(--canvas)] px-4 py-5 sm:px-8 sm:py-8 lg:px-12"><div className="mx-auto max-w-6xl"><header className="flex flex-col gap-3 border-b border-[var(--line)] pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium uppercase tracking-[.18em] text-[var(--brand)]">Doctor portal</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">My Profile</h1><p className="mt-2 text-[var(--muted)]">Keep your practice details and appointment availability current.</p></div><Link className="font-semibold text-[var(--brand)] hover:underline" href="/doctor/dashboard">Back to dashboard</Link></header>
    <div className="mt-7 grid gap-7 lg:grid-cols-[1.1fr_.9fr]"><form onSubmit={saveProfile} className="rounded-xl border border-[var(--line)] bg-white p-5 shadow-sm sm:p-6"><h2 className="text-xl font-semibold">Professional details</h2><p className="mt-1 text-sm text-[var(--muted)]">This information appears across your Doctor Portal.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Full name" value={profile.name} onChange={(value) => updateProfileField("name", value)} /><Field label="Email" type="email" value={profile.email} onChange={(value) => updateProfileField("email", value)} /><Field label="Specialization" value={profile.specialization} onChange={(value) => updateProfileField("specialization", value)} /><Field label="Qualification" value={profile.qualification} onChange={(value) => updateProfileField("qualification", value)} /><Field label="Experience (years)" type="number" value={String(profile.experienceYears)} onChange={(value) => updateProfileField("experienceYears", value)} /><Field label="Phone number" type="tel" value={profile.phone} onChange={(value) => updateProfileField("phone", value)} /></div><label className="mt-4 block text-sm font-medium">Clinic address<input className={fieldClass} value={profile.clinicAddress} onChange={(event) => updateProfileField("clinicAddress", event.target.value)} /></label><label className="mt-4 block text-sm font-medium">Professional bio<textarea className={`${fieldClass} min-h-28 resize-y`} value={profile.bio} onChange={(event) => updateProfileField("bio", event.target.value)} /></label><label className="mt-4 block text-sm font-medium">Profile image URL <span className="font-normal text-[var(--muted)]">(optional)</span><input className={fieldClass} type="url" value={profile.profileImage} onChange={(event) => updateProfileField("profileImage", event.target.value)} /></label>{profileError && <p className="mt-4 text-sm text-red-700" role="alert">{profileError}</p>}{message && <p className="mt-4 text-sm font-medium text-emerald-700" role="status">{message}</p>}<button className="mt-5 rounded-lg bg-[var(--brand)] px-5 py-2.5 text-sm font-semibold text-white hover:bg-[var(--brand-deep)] disabled:opacity-60" type="submit" disabled={isSavingProfile}>{isSavingProfile ? "Saving profile..." : "Save profile"}</button></form>
      <section className="rounded-xl border border-[var(--line)] bg-white p-5 shadow-sm sm:p-6"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-lg bg-emerald-50 text-[var(--brand)]"><CalendarPlus className="size-5" /></span><div><h2 className="text-xl font-semibold">Appointment availability</h2><p className="mt-1 text-sm text-[var(--muted)]">{availableCount} available {availableCount === 1 ? "slot" : "slots"}</p></div></div><form className="mt-6" onSubmit={addSlots}><div className="grid gap-4 sm:grid-cols-2"><Field label="Start date" type="date" min={today()} value={slotForm.date} onChange={(date) => setSlotForm((current) => ({ ...current, date }))} /><Field label="End date" type="date" min={slotForm.date} value={slotForm.endDate} disabled={!slotForm.isRecurring} onChange={(endDate) => setSlotForm((current) => ({ ...current, endDate }))} /><Field label="Start time" type="time" value={slotForm.startTime} onChange={(startTime) => setSlotForm((current) => ({ ...current, startTime }))} /><Field label="End time" type="time" value={slotForm.endTime} onChange={(endTime) => setSlotForm((current) => ({ ...current, endTime }))} /></div><label className="mt-5 flex cursor-pointer items-center gap-3 text-sm font-medium"><input className="size-4 accent-[var(--brand)]" type="checkbox" checked={slotForm.isRecurring} onChange={(event) => setSlotForm((current) => ({ ...current, isRecurring: event.target.checked }))} />Repeat weekly</label>{slotForm.isRecurring && <fieldset className="mt-3"><legend className="text-sm font-medium">Repeat on</legend><div className="mt-2 flex flex-wrap gap-2">{weekdayNames.map((day, index) => <label key={day} className={`cursor-pointer rounded-full border px-3 py-1.5 text-sm ${slotForm.daysOfWeek.includes(index) ? "border-[var(--brand)] bg-emerald-50 text-[var(--brand-deep)]" : "border-[var(--line)]"}`}><input className="sr-only" type="checkbox" checked={slotForm.daysOfWeek.includes(index)} onChange={() => toggleDay(index)} />{day}</label>)}</div></fieldset>}{slotError && <p className="mt-4 text-sm text-red-700" role="alert">{slotError}</p>}<button className="mt-5 inline-flex items-center gap-2 rounded-lg bg-[var(--brand)] px-5 py-2.5 text-sm font-semibold text-white hover:bg-[var(--brand-deep)]" type="submit"><Clock3 className="size-4" />Add availability</button></form></section></div>
    <section className="mt-7 overflow-hidden rounded-xl border border-[var(--line)] bg-white shadow-sm"><div className="border-b border-[var(--line)] px-5 py-4 sm:px-6"><h2 className="text-xl font-semibold">Manage slots</h2><p className="mt-1 text-sm text-[var(--muted)]">Recurring availability is expanded into individual dates.</p></div>{slots.length === 0 ? <p className="px-6 py-10 text-center text-sm text-[var(--muted)]">No availability added yet.</p> : <ul className="divide-y divide-[var(--line)]">{slots.map((slot) => <li className="flex items-center justify-between gap-4 px-5 py-4 sm:px-6" key={slot.id}><div><p className="font-semibold">{formatDate(slot.date)} · {formatTime(slot.startTime)}–{formatTime(slot.endTime)}</p><p className="mt-1 text-sm text-[var(--muted)]">{slot.isRecurring ? "Weekly recurring slot" : "One-time slot"} · <span className="capitalize">{slot.status}</span></p></div>{slot.status === "available" ? <button className="rounded-lg p-2 text-red-700 hover:bg-red-50" type="button" onClick={() => deleteSlot(slot)} aria-label={`Delete slot on ${slot.date}`}><Trash2 className="size-4" /></button> : <div className="text-right"><button className="rounded-lg p-2 text-slate-300" type="button" disabled aria-label={`Delete slot on ${slot.date} is unavailable`} title="Cancel the appointment before deleting this slot"><Trash2 className="size-4" /></button><p className="text-xs text-[var(--muted)]">Cancel the appointment first.</p></div>}</li>)}</ul>}</section></div></main>;
}

function Field({ label, value, onChange, type = "text", min, disabled = false }: { label: string; value: string; onChange: (value: string) => void; type?: "text" | "email" | "number" | "tel" | "url" | "date" | "time"; min?: string; disabled?: boolean }) { return <label className="block text-sm font-medium">{label}<input className={fieldClass} type={type} min={min} disabled={disabled} value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function today(): string { return new Date().toISOString().slice(0, 10); }
function addDays(days: number): string { const date = new Date(); date.setDate(date.getDate() + days); return date.toISOString().slice(0, 10); }
function recurringDates(start: string, end: string, days: number[]): string[] { const dates: string[] = []; const cursor = new Date(`${start}T00:00:00`); const last = new Date(`${end}T00:00:00`); while (cursor <= last) { if (days.includes(cursor.getDay())) dates.push(cursor.toISOString().slice(0, 10)); cursor.setDate(cursor.getDate() + 1); } return dates; }
function formatDate(date: string): string { return new Date(`${date}T00:00:00`).toLocaleDateString("en-IN", { weekday: "short", month: "short", day: "numeric" }); }
function formatTime(time: string): string { return new Date(`2000-01-01T${time}:00`).toLocaleTimeString("en-IN", { hour: "numeric", minute: "2-digit" }); }
